version: '3.4'

services:
    db:
        image: mariadb
        restart: always
        ports: 
            - '33061:3306'
        env_file:
            - ./config/db.env
        volumes: 
            - db:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports:
            - '8082:8080'
    app:
        restart: always
        build: 
            dockerfile: Dockerfile.app
            context: ./app
        ports: 
            - '8080:80'
    api:
        restart: always
        build: 
            dockerfile: Dockerfile.api
            context: ./api
        ports:
            - '8081:80'
volumes: 
    db: 