// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(DockerAppContext))]
    partial class DockerAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("person_id")
                        .HasColumnType("int(11)");

                    b.Property<int?>("PersonAge")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("person_age")
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("PersonName")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("person_name")
                        .HasColumnType("varchar(500)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(500)
                        .IsUnicode(false);

                    b.HasKey("PersonId");

                    b.ToTable("person");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("mediumint(8) unsigned");

                    b.Property<string>("City")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("city")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Company")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("company")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("country")
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("date_created")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("date_modified")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("email")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("FirstName")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("first_name")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("last_name")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("phone")
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("StreetAddress")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("street_address")
                        .HasColumnType("varchar(255)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Zip")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("zip")
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("'NULL'")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}
